name: Build FAISS index

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Cache HuggingFace caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/huggingface
            ~/.cache/torch
          key: ${{ runner.os }}-hf-${{ hashFiles('build_index.py') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build FAISS index
        run: python build_index.py

      - name: Commit and push index files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.faiss texts.json metas.json
          git commit -m "chore: update FAISS index" || echo "No changes to commit"
          git push
        env:
          # automatically provided by actions/checkout
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
